### ISSUE TITLE
Add README command to generate uppercase README.md 

### ISSUE THREAD

**Issue by androiddevnotes** [Sharkaboi/EmptyGit#2]
**Is your feature request related to a problem? Please describe.**
README is more commonly used than the lowercase readme as a naming convention. The README file's name is generally written in uppercase letters.

**Describe the solution you'd like**
Add additional command preferably called README to generate README.md in uppercase form.

**Describe alternatives you've considered**
n/a

**Additional context**
README naming: https://en.wikipedia.org/wiki/README

**Comment by Sharkaboi** [comment]
Hey
Thanks for the suggestion!
I'll change it to where the default is `README.md` and an optional flag could be set for lowercase `readme.md`.
